# Generated by Django 2.1.1 on 2018-09-06 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='flag',
            new_name='activate',
        ),
    ]
